### ISSUE TITLE
Possible Improvement: Using SOEM as Submodule

### ISSUE THREAD

**Issue by rkeatin3** [mgruhler/soem#11]
I was having trouble compiling this package in ROS to work with robotiq_ethercat, so I ended up starting from scratch with the base SOEM repo. I got it to compile with minimal work by creating a ROS package with the following files and SOEM as a submodule:

[CMakeLists.txt](https://github.com/smits/soem/files/1322525/CMakeLists.txt)
[package.xml](https://github.com/smits/soem/files/1322527/package.xml.txt)
 
Could this help resolve some of the other issues for this package? Any other feedback?

**Comment by mgruhler** [comment]
@rkeatin3 thanks for the suggestion.
There is a problem in the directory layout of the soem headers, though, see #17, especially with how to install it.
How to use the latest soem release is tracked in #16, i linked to this issue therein, as I like the submodule idea.

Without knowing the details, I think that your problems could have been resolved using the workaround described in the [Usage section of the README.md](https://github.com/mgruhler/soem#Usage).

I'll close this, but feel free to reopen if you feel your issue is not tracked enough in the linked issues above.
